"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1j1+f^+eoqe+=m(3=5@2b7$f&v=qd(ow9rapx_((q%okk2-uom'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework',

    'solar'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'x-api-key',
    'content-type',
    'Authorization'
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'Asia/Tashkent'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),

}

JWT_USE = True
ACCESS_TOKEN_LIFETIME = timedelta(days=7)
REFRESH_TOKEN_LIFETIME = timedelta(days=14)

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': ACCESS_TOKEN_LIFETIME,
    'REFRESH_TOKEN_LIFETIME': REFRESH_TOKEN_LIFETIME,
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
SOLAR = {
    1: {
        'A+': 'B409',
        'A-': 'B410',
        'R+': 'B411',
        'R-': 'B412',
        'P_total': 'G275',
        'P_1': 'G276',
        'P_2': 'G277',
        'P_3': 'G278',
        'U_1': 'G279',
        'U_2': 'G280',
        'U_3': 'G281',
        'I_1': 'G282',
        'I_2': 'G283',
        'I_3': 'G284',
        'coefficient': 300,
        "count": 5
    },
    2: {
        'A+': 'B413',
        'A-': 'B414',
        'R+': 'B415',
        'R-': 'B416',
        'P_total': 'G286',
        'P_1': 'G287',
        'P_2': 'G288',
        'P_3': 'G289',
        'U_1': 'G290',
        'U_2': 'G291',
        'U_3': 'G292',
        'I_1': 'G293',
        'I_2': 'G294',
        'I_3': 'G295',
        'coefficient': 300,
        "count": 6,
    },
    3: {
        'A+': 'B433',
        'A-': 'B434',
        'R+': 'B435',
        'R-': 'B436',
        'P_total': 'G303',
        'P_1': 'G304',
        'P_2': 'G305',
        'P_3': 'G306',
        'U_1': 'G307',
        'U_2': 'G308',
        'U_3': 'G309',
        'I_1': 'G310',
        'I_2': 'G311',
        'I_3': 'G312',
        'coefficient': 80,
        "count": 6,
    },
    4: {
        'A+': 'B437',
        'A-': 'B438',
        'R+': 'B439',
        'R-': 'B440',
        'P_total': 'G318',
        'P_1': 'G319',
        'P_2': 'G320',
        'P_3': 'G321',
        'U_1': 'G322',
        'U_2': 'G323',
        'U_3': 'G324',
        'I_1': 'G325',
        'I_2': 'G326',
        'I_3': 'G327',
        'coefficient': 120,
        "count": 5
    }
}
